/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mitac_i2c_Vibrator */

#ifndef _Included_com_mitac_i2c_Vibrator
#define _Included_com_mitac_i2c_Vibrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mitac_i2c_Vibrator
 * Method:    setIntensity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mitac_i2c_Vibrator_setIntensity
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mitac_i2c_Vibrator
 * Method:    getIntensity
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_com_mitac_i2c_Vibrator_getIntensity
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
